joker_backend/Joker/config/routes.rb
Joker::Application.routes.draw do
  resources :tokens

  resources :app_accounts

  resources :apps

  resources :favorites

  resources :spams

  resources :likes

  resources :tags do
    collection do
      get 'find'
    end
  end

  resources :voices do
    collection do
      get 'my_voices'
    end
    member do
      post 'update_tags'
    end
  end

  resources :users do
    collection do
      post 'change_password'
      post 'init_session'
      get 'login_form'
      get 'logout'
      post 'login'
      post 'forgot_password'
    end
    member do
      get 'restore_password'
    end
  end

end

joker_backend/Joker/app/models/app_account.rb
class AppAccount < ActiveRecord::Base
  attr_accessible :app_id, :login, :password, :time, :max_time, :last_usage
  belongs_to :app
  has_many :voices, :foreign_key => 'app_account_id'
  #TODO add unique index for app_id<=>login beter app.system<=>login

  validates :login,
    :presence => {:message => 'login is required'}
  validates :password,
    :presence => {:message => 'password is required'}

  after_update :update_app

  def update_app
    if self.time_changed?
      self.app.time = self.app.time + self.time - self.time_was
      self.app.save
    end
  end
end

joker_backend/Joker/app/controllers/app_accounts_controller.rb
class AppAccountsController < ApplicationController
  # GET /app_accounts
  # GET /app_accounts.json
  def index
    @app_accounts = AppAccount.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @app_accounts }
    end
  end

  # GET /app_accounts/1
  # GET /app_accounts/1.json
  def show
    @app_account = AppAccount.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app_account }
    end
  end

  # GET /app_accounts/new
  # GET /app_accounts/new.json
  def new
    @app_account = AppAccount.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app_account }
    end
  end

  # GET /app_accounts/1/edit
  def edit
    @app_account = AppAccount.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app_account }
    end
  end

  # POST /app_accounts
  # POST /app_accounts.json
  def create
    @app_account = AppAccount.new(params[:app_account])
    @app_account.last_usage = Time.new

    respond_to do |format|
      if @app_account.save
        format.html { redirect_to @app_account, notice: 'App account was successfully created.' }
        format.json { render json: @app_account, status: :created, location: @app_account }
      else
        format.html { render action: "new" }
        format.json { render json: @app_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /app_accounts/1
  # PUT /app_accounts/1.json
  def update
    @app_account = AppAccount.find(params[:id])

    respond_to do |format|
      if @app_account.update_attributes(params[:app_account])
        format.html { redirect_to @app_account, notice: 'App account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_accounts/1
  # DELETE /app_accounts/1.json
  def destroy
    @app_account = AppAccount.find(params[:id])
    @app_account.destroy

    respond_to do |format|
      format.html { redirect_to app_accounts_url }
      format.json { head :no_content }
    end
  end
end

joker_backend/Joker/app/helpers/app_accounts_helper.rb
module AppAccountsHelper
end

joker_backend/Joker/app/views/app_accounts/_form.html.haml
= form_for @app_account do |f|
  - if @app_account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@app_account.errors.count, "error")} prohibited this app_account from being saved:"
      %ul
        - @app_account.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :login
    = f.text_field :login
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :app_id
    = f.number_field :app_id
  .field
    = f.label :time
    = f.number_field :time
  .field
    = f.label :max_time
    = f.number_field :max_time
  .actions
    = f.submit 'Save'

joker_backend/Joker/app/views/app_accounts/edit.html.haml
%h1 Editing app_account

= render 'form'

= link_to 'Show', @app_account
\|
= link_to 'Back', app_accounts_path

joker_backend/Joker/app/views/app_accounts/index.html.haml
%h1 Listing app_accounts

%table
  %tr
    %th Login
    %th Password
    %th App
    %th Time
    %th Max Time
    %th Last Usage
    %th
    %th
    %th

  - @app_accounts.each do |app_account|
    %tr
      %td= app_account.login
      %td= app_account.password
      %td= app_account.app_id
      %td= app_account.time
      %td= app_account.max_time
      %td= app_account.last_usage
      %td= link_to 'Show', app_account
      %td= link_to 'Edit', edit_app_account_path(app_account)
      %td= link_to 'Destroy', app_account, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New App account', new_app_account_path

joker_backend/Joker/app/views/app_accounts/new.html.haml
%h1 New app_account

= render 'form'

= link_to 'Back', app_accounts_path

joker_backend/Joker/app/views/app_accounts/show.html.haml
%p#notice= notice

%p
  %b Login:
  = @app_account.login
%p
  %b Password:
  = @app_account.password
%p
  %b App:
  = @app_account.app_id
%p
  %b Time:
  = @app_account.time

= link_to 'Edit', edit_app_account_path(@app_account)
\|
= link_to 'Back', app_accounts_path