joker_backend/Joker/config/routes.rb
Joker::Application.routes.draw do
  resources :tokens

  resources :app_accounts

  resources :apps

  resources :favorites

  resources :spams

  resources :likes

  resources :tags do
    collection do
      get 'find'
    end
  end

  resources :voices do
    collection do
      get 'my_voices'
    end
    member do
      post 'update_tags'
    end
  end

  resources :users do
    collection do
      post 'change_password'
      post 'init_session'
      get 'login_form'
      get 'logout'
      post 'login'
      post 'forgot_password'
    end
    member do
      get 'restore_password'
    end
  end

end

joker_backend/Joker/app/views/apps/_form.html.haml
= form_for @app do |f|
  - if @app.errors.any?
    #error_explanation
      %h2= "#{pluralize(@app.errors.count, "error")} prohibited this app from being saved:"
      %ul
        - @app.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :system
    = f.text_field :system
  .field
    = f.label :client_id
    = f.text_field :client_id
  .field
    = f.label :client_secret
    = f.text_field :client_secret
  .field
    = f.label :time
    = f.number_field :time
  .actions
    = f.submit 'Save'

joker_backend/Joker/app/views/apps/edit.html.haml
%h1 Editing app

= render 'form'

= link_to 'Show', @app
\|
= link_to 'Back', apps_path

joker_backend/Joker/app/views/apps/index.html.haml
%h1 Listing apps

%table
  %tr
    %th System
    %th Client
    %th Client secret
    %th Time
    %th
    %th
    %th

  - @apps.each do |app|
    %tr
      %td= app.system
      %td= app.client_id
      %td= app.client_secret
      %td= app.time
      %td= link_to 'Show', app
      %td= link_to 'Edit', edit_app_path(app)
      %td= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New App', new_app_path

joker_backend/Joker/app/views/apps/new.html.haml
%h1 New app

= render 'form'

= link_to 'Back', apps_path

joker_backend/Joker/app/views/apps/show.html.haml
%p#notice= notice

%p
  %b System:
  = @app.system
%p
  %b Client:
  = @app.client_id
%p
  %b Client secret:
  = @app.client_secret
%p
  %b Time:
  = @app.time

= link_to 'Edit', edit_app_path(@app)
\|
= link_to 'Back', apps_path