joker_backend/Joker/config/routes.rb
Joker::Application.routes.draw do
  resources :tokens

  resources :app_accounts

  resources :apps

  resources :favorites

  resources :spams

  resources :likes

  resources :tags do
    collection do
      get 'find'
    end
  end

  resources :voices do
    collection do
      get 'my_voices'
    end
    member do
      post 'update_tags'
    end
  end

  resources :users do
    collection do
      post 'change_password'
      post 'init_session'
      get 'login_form'
      get 'logout'
      post 'login'
      post 'forgot_password'
    end
    member do
      get 'restore_password'
    end
  end

end

joker_backend/Joker/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :tag
  has_and_belongs_to_many :voices
  validates :tag,
    :presence => { :message => "tag is required" },
    :uniqueness => {:message => 'tag already exists'}

  before_save :downcase_tags

  protected
  def downcase_tags
    self.tag = self.tag.downcase
  end

end

joker_backend/Joker/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/find
  # GET /tags/find.json
  def find
    @tags = Tag.where("tag LIKE '#{params[:findtag]}%'").limit(5)
  respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @like }
    end
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

joker_backend/Joker/app/helpers/tags_helper.rb
module TagsHelper
end

joker_backend/Joker/app/views/tags/_form.html.haml
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :tag
    = f.text_field :tag
  .actions
    = f.submit 'Save'

joker_backend/Joker/app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

joker_backend/Joker/app/views/tags/index.html.haml
%h1 Listing tags

%table
  %tr
    %th Tag
    %th
    %th
    %th

  - @tags.each do |tag|
    %tr
      %td= tag.tag
      %td= link_to 'Show', tag
      %td= link_to 'Edit', edit_tag_path(tag)
      %td= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Tag', new_tag_path

joker_backend/Joker/app/views/tags/new.html.haml
%h1 New tag

= render 'form'

= link_to 'Back', tags_path

joker_backend/Joker/app/views/tags/show.html.haml
%p#notice= notice

%p
  %b Tag:
  = @tag.tag

= link_to 'Edit', edit_tag_path(@tag)
\|
= link_to 'Back', tags_path