joker_backend/Joker/config/routes.rb
Joker::Application.routes.draw do
  resources :tokens

  resources :app_accounts

  resources :apps

  resources :favorites

  resources :spams

  resources :likes

  resources :tags do
    collection do
      get 'find'
    end
  end

  resources :voices do
    collection do
      get 'my_voices'
    end
    member do
      post 'update_tags'
    end
  end

  resources :users do
    collection do
      post 'change_password'
      post 'init_session'
      get 'login_form'
      get 'logout'
      post 'login'
      post 'forgot_password'
    end
    member do
      get 'restore_password'
    end
  end

end

joker_backend/Joker/app/models/token.rb
class Token < ActiveRecord::Base
  attr_accessible :token, :user_id, :trusted
  belongs_to :user

  #TODO do not create token from browser

  validates :user_id,
    :presence => { :message => "user_id is required" },
    :uniqueness => {:message => 'token for this user already exists'}

  validate :validate_user_id

  before_create :init_token
  before_update :restrict_updating

  def validate_user_id
    user = User.find(self.user_id)
  rescue
    errors.add(:user_id, "user_id is not valid")
  end

  protected
  def init_token
    uuid = UUID.new
    self.token = uuid.generate
  end

  protected
  def restrict_updating
    return false
  end

end

joker_backend/Joker/app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  # GET /tokens
  # GET /tokens.json
  def index
    @tokens = Token.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tokens }
    end
  end

  # GET /tokens/1
  # GET /tokens/1.json
  def show
    @token = Token.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @token }
    end
  end

  # GET /tokens/new
  # GET /tokens/new.json
  def new
    @token = Token.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @token }
    end
  end

  # GET /tokens/1/edit
  def edit
    @token = Token.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @token }
    end
  end

  # POST /tokens
  # POST /tokens.json
  def create
    @token = Token.new(params[:token])

    respond_to do |format|
      if @token.save
        format.html { redirect_to @token, notice: 'Token was successfully created.' }
        format.json { render json: @token, status: :created, location: @token }
      else
        format.html { render action: "new" }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tokens/1
  # PUT /tokens/1.json
  def update
    @token = Token.find(params[:id])

    respond_to do |format|
      if @token.update_attributes(params[:token])
        format.html { redirect_to @token, notice: 'Token was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    @token = Token.find(params[:id])
    @token.destroy

    respond_to do |format|
      format.html { redirect_to tokens_url }
      format.json { head :no_content }
    end
  end
end

joker_backend/Joker/app/helpers/tokens_helper.rb
module TokensHelper
end

joker_backend/Joker/app/views/tokens/_form.html.haml
= form_for @token do |f|
  - if @token.errors.any?
    #error_explanation
      %h2= "#{pluralize(@token.errors.count, "error")} prohibited this token from being saved:"
      %ul
        - @token.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :token
    = f.text_field :token
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions
    = f.submit 'Save'

joker_backend/Joker/app/views/tokens/edit.html.haml
%h1 Editing token

= render 'form'

= link_to 'Show', @token
\|
= link_to 'Back', tokens_path

joker_backend/Joker/app/views/tokens/index.html.haml
%h1 Listing tokens

%table
  %tr
    %th Token
    %th User
    %th
    %th
    %th

  - @tokens.each do |token|
    %tr
      %td= token.token
      %td= token.user_id
      %td= link_to 'Show', token
      %td= link_to 'Edit', edit_token_path(token)
      %td= link_to 'Destroy', token, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Token', new_token_path

joker_backend/Joker/app/views/tokens/new.html.haml
%h1 New token

= render 'form'

= link_to 'Back', tokens_path

joker_backend/Joker/app/views/tokens/show.html.haml
%p#notice= notice

%p
  %b Token:
  = @token.token
%p
  %b User:
  = @token.user_id

= link_to 'Edit', edit_token_path(@token)
\|
= link_to 'Back', tokens_path